name: authentication_repository
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

